### ISSUE TITLE
Back Button not visible from settings>>context

### ISSUE THREAD

**Issue by dhruv0000** [internetarchive/wayback-machine-chrome#431] opened 2020-02-25 07:57 UTC
**Describe the bug**
There is no way to toggle back from the context sub-setting

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the extension
2. Click on settings
3. Select 'Context' Sub-option

**Expected behavior**
The back button should be visible.

**Screenshots**
![error1](https://user-images.githubusercontent.com/44001539/75226321-37d9f100-57d2-11ea-9fc1-df075be916dc.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 80.0.3987.116

**Comment by dhruv0000** [comment] 2020-02-25 07:58
I would like to work on this issue.

**Comment by sanyam99ag** [comment] 2020-03-30 19:35
@dhruv0000 Yes, by increasing the dimensions the problem will be solved but wouldn't it be better if there can be a scroller in spite of increasing the size of the popup window.

**Comment by tikhsuP** [comment] 2020-04-17 09:07
@sanyam99ag 
![Capture4441](https://user-images.githubusercontent.com/42881874/79552527-c70bd280-80b8-11ea-8fe1-868be0f8a69f.PNG)
![Capture444411](https://user-images.githubusercontent.com/42881874/79552610-e0ad1a00-80b8-11ea-8e1b-cd6d7c6e0c48.PNG)

I believe this is what we seek here.
I would like to work on it.

**Comment by shucon** [comment] 2020-05-15 21:50
I'm not able to reproduce this issue on my local computer with the latest master branch
![Screenshot from 2020-05-16 03-17-49](https://user-images.githubusercontent.com/22860775/82099151-33afd680-9724-11ea-8b82-e475c926dc2e.png)

**Comment by tikhsuP** [comment] 2020-05-15 21:55
@shucon, this issue is fixed as the extension has been redesigned. This issue will be closed shortly.
Thanks for your interest :)

**Comment by shucon** [comment] 2020-05-15 22:14
Please link it with the PR that closed it. It's always helpful :)

**Closed** 2020-05-16 00:03 UTC

**Comment by cgorringe** [comment] 2020-05-16 00:54
There's been multiple PRs that have updated this UI, but latest was #495.
